require('dotenv').config();

module.exports = {
    PORT: process.env.PORT,
    DB_HOST: process.env.DB_HOST,
    DB_PORT: process.env.DB_PORT,
    DB_NAME: process.env.DB_NAME,
    DB_USER: process.env.DB_USER,
    DB_PASSWORD: process.env.DB_PASSWORD,
    JWT_SECRET: process.env.JWT_SECRET,
    NODE_ENV: process.env.NODE_ENV,
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
    ENCRYPT_DYCRYPT_AES_KEY: process.env.ENCRYPT_DYCRYPT_AES_KEY,
    ENCRYPT_DYCRYPT_DATA_KEY: process.env.ENCRYPT_DYCRYPT_DATA_KEY,
    MESSAGE_DOMAIN: process.env.MESSAGE_DOMAIN,
    MESSAGE_USERNAME: process.env.MESSAGE_USERNAME,
    MESSAGE_PASSWORD: process.env.MESSAGE_PASSWORD,
    MESSAGE_SENDERID: process.env.MESSAGE_SENDERID,
    MESSAGE_ROUTE: process.env.MESSAGE_ROUTE,
    MESSAGE_PEID: process.env.MESSAGE_PEID,
    MESSAGE_TEMPID: process.env.MESSAGE_TEMPID,
    NODEMAILER_HOST: process.env.NODEMAILER_HOST,
    NODEMAILER_PORT: process.env.NODEMAILER_PORT,
    NODEMAILER_SECURE: process.env.NODEMAILER_SECURE === 'true',
    NODEMAILER_USER: process.env.NODEMAILER_USER,
    NODEMAILER_PASS: process.env.NODEMAILER_PASS,
    ADMIN: process.env.ADMIN,
    EMPLOYEE: process.env.EMPLOYEE,
    MANAGER: process.env.MANAGER,
}